In [7]:
import numpy as np
import pandas as pd
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

In [8]:
X,y=make_classification(n_samples=1000,n_features=5,random_state=123)

In [9]:
X

array([[ 0.87728113, -0.59642825,  0.44019839, -0.52108094,  0.31432298],
       [ 0.55856502, -0.41451292,  0.813623  , -0.54325372,  0.14734302],
       [-0.90289911,  0.38303337, -0.71157267, -0.86768895, -0.67394137],
       ...,
       [ 1.7713853 , -0.96445461,  0.99337636,  0.40674576,  0.99881985],
       [-1.19977749,  0.48167954,  1.47831033, -1.31903526, -0.93698258],
       [ 0.33976266, -0.29183452, -0.82476815, -0.57191024,  0.02935597]])

In [10]:
y

array([0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,

In [11]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [12]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((700, 5), (300, 5), (700,), (300,))

In [13]:
model=LogisticRegression()

In [14]:
#Training model here
model.fit(X_train,y_train)

LogisticRegression()

In [16]:
model.score(X_train,y_train)
#logistic regression is able to 94% data

0.9428571428571428

In [17]:
y_pred=model.predict(X_test)

In [18]:
accuracy_score(y_test,y_pred)

0.97

In [19]:
confusion_matrix(y_test,y_pred)

array([[149,   3],
       [  6, 142]], dtype=int64)

In [ ]:
# overfitting mean
# train accuracy is very good
# and test accruacy is not

# train_accuracy-test_accuracy

# underfitting means
# train accuracy and test accuracy both are not good